namespace Rollback.World.CustomEnums
{
    public enum JobIds : sbyte
    {
        Base = 1,
        Bucheron = 2,
        ForgeurEpee = 11,
        SculpteurArc = 13,
        ForgeurMarteau = 14,
        Cordonier = 15,
        Bijoutier = 16,
        ForgeurDague = 17,
        SculpteurBaton = 18,
        SculpteurBaguette = 19,
        ForgeurPelle = 20,
        Mineur = 24,
        Boulanger = 25,
        Alchimiste = 26,
        Tailleur = 27,
        Paysan = 28,
        ForgeurHaches = 31,
        Pecheur = 36,
        Chasseur = 41,
        FmDague = 43,
        FmEpee = 44,
        FmMarteau = 45,
        FmPelle = 46,
        FmHaches = 47,
        FmArc = 48,
        FmBaguette = 49,
        FmBaton = 50,
        Boucher = 56,
        Poissonnier = 58,
        ForgeurBouclier = 60,
        Cordomage = 62,
        Joaillomage = 63,
        Costumage = 64,
        Bricoleur = 65,
    }
}
